import { useState, useEffect } from 'react';
import { TerminalView } from './views/Terminal';
import { SingleCommandView } from './views/SingleCommand';

export function App() {
  const [capability, setCapability] = useState<{
    capId: string;
    S: string;
  } | null>(null);
  
  const [terminalMode, setTerminalMode] = useState(true);
  
  useEffect(() => {
    const path = window.location.pathname.split('/').filter(Boolean);
    const hash = window.location.hash;
    
    // Check URL format: /cap/{capId}#S={secret}
    if (path.length === 2 && path[0] === 'cap' && hash.startsWith('#S=')) {
      setCapability({
        capId: path[1]!,
        S: hash.substring(3),
      });
    }
    
    // Check for terminal=false query param
    const params = new URLSearchParams(window.location.search);
    if (params.get('terminal') === 'false') {
      setTerminalMode(false);
    }
  }, []);
  
  if (!capability) {
    return (
      <div className="app">
        <div className="header">
          <h1>Entangle</h1>
          <p>No capability provided. Use a link generated by entangle-agent.</p>
        </div>
      </div>
    );
  }
  
  return terminalMode ? (
    <TerminalView capability={capability} />
  ) : (
    <SingleCommandView capability={capability} />
  );
}