import { useState, useEffect, useRef } from 'react';
import { InvokeView } from './views/Invoke';

export function App() {
  const [capability, setCapability] = useState<{
    namespace: string;
    capId: string;
    S: string;
  } | null>(null);
  
  useEffect(() => {
    const path = window.location.pathname.split('/').filter(Boolean);
    const hash = window.location.hash;
    
    if (path.length === 2 && hash.startsWith('#S=')) {
      setCapability({
        namespace: path[0],
        capId: path[1],
        S: hash.substring(3),
      });
    }
  }, []);
  
  if (!capability) {
    return (
      <div className="app">
        <div className="header">
          <h1>Entangle</h1>
          <p>No capability provided. Use a link generated by entangle-agent.</p>
        </div>
      </div>
    );
  }
  
  return <InvokeView capability={capability} />;
}